TorchServe Management API RCE
doyensec/tsunami-security-scanner-plugins pull request #8
Opened 2023-12-19 11:14 UTC by execveat

There are multiple detection levels so it should fall off gracefully, depending on what's available:

- Static: need to manually upload infected model somewhere
- Local: plugins spawns HTTP server to serve model
- SSRF: ask TorchServe to download model from the callback server - the RCE isn't tested directly, but if there is callback, `allow_urls` probably aren't set so it should be vulnerable
- Basic: callback server isn't available and other options haven't been set, fall back to just fingerprinting Management API

2023-12-19 16:18 UTC, dawidg-doyen requested changes

2023-12-19 16:18 UTC, dawidg-doyen commented on doyensec/detectors/rce/torchserve/src/main/java/com/google/tsunami/plugins/detectors/rce/torchserve/TorchServeExploiter.java
Typo in there "fingerpint"

2023-12-20 13:43 UTC, execveat commented on doyensec/detectors/rce/torchserve/src/main/java/com/google/tsunami/plugins/detectors/rce/torchserve/TorchServeManagementApiDetector.java
> +  static final String REPORT_RECOMMENDATION =
Please advise how to achieve this. I tried various approaches, but the problem is that Tsunami handles command line arguments and config file differently. So the CLI args are defined in [TorchServeManagementApiArgs](https://github.com/doyensec/tsunami-security-scanner-plugins/blob/torchserve_rce/doyensec/detectors/rce/torchserve/src/main/java/com/google/tsunami/plugins/detectors/rce/torchserve/TorchServeManagementApiArgs.java) and the config file options are in [TorchServeManagementApiConfig](https://github.com/doyensec/tsunami-security-scanner-plugins/blob/torchserve_rce/doyensec/detectors/rce/torchserve/src/main/java/com/google/tsunami/plugins/detectors/rce/torchserve/TorchServeManagementApiConfig.java). It looks like these could be combined in a single class implementing CliOption interface and annotated with both ConfigProperties and @Parameters, but the order of execution is undefined and I didn't see any other plugins doing this so far, so I didn't risk it.

I'm mergin CLI args and config file options manually in the [TorchServeExploiter.Details](https://github.com/doyensec/tsunami-security-scanner-plugins/blob/3007826c30c37a155f0bba0cbcbf5eb98fe8f408/doyensec/detectors/rce/torchserve/src/main/java/com/google/tsunami/plugins/detectors/rce/torchserve/TorchServeExploiter.java#L99) class, this could be moved to TorchServeManagementApiDetector, but I'm not convinced it will improve readability.

As an aside, I think we should write down CLI args and config file unification as a future improvement idea as this should really happen in Tsunami core.

2023-12-20 14:56 UTC, execveat commented on doyensec/detectors/rce/torchserve/src/main/resources/model/MAR-INF/MANIFEST.json
> +      "modelName": "somerandomname",
Done.

2023-12-20 14:56 UTC, execveat commented on doyensec/detectors/rce/torchserve/src/main/java/com/google/tsunami/plugins/detectors/rce/torchserve/TorchServeManagementApiDetector.java
> +  static final String REPORT_PUBLISHER = "TSUNAMI_COMMUNITY";
Done.

2023-12-20 14:56 UTC, execveat commented on doyensec/detectors/rce/torchserve/src/main/java/com/google/tsunami/plugins/detectors/rce/torchserve/TorchServeManagementApiDetector.java
> +        logger.atInfo().log("Looking at service %s", service);
Done.

2023-12-20 14:56 UTC, execveat commented on doyensec/detectors/rce/torchserve/src/main/java/com/google/tsunami/plugins/detectors/rce/torchserve/TorchServeExploiter.java
Done.

2023-12-20 14:56 UTC, execveat commented on doyensec/detectors/rce/torchserve/src/main/resources/model/model.py
> +import hashlib
Done.

2023-12-20 15:03 UTC, execveat commented
Thank you, @dawidg-doyen! I fixed most of the issues, but there's one that remains, please check it.

What do you think about the current report severity ([see here](https://github.com/doyensec/tsunami-security-scanner-plugins/blob/c0002c67094a7d487dbcb92cd39685687a5ac8cd/doyensec/detectors/rce/torchserve/src/main/java/com/google/tsunami/plugins/detectors/rce/torchserve/TorchServeExploiter.java#L142))? Currently we set severity to Critical if the command execution has been verified and High otherwise.

In practice, that means a High severity finding will be created if the plugin was executed without any options and without the callback server available, as then we just stop at Management API fingerprinting. But there's inconsistency because if callback server is available or more advanced mode was selected we will raise Critical for confirmed code  execution, but we will not produce any findings for plain Management API in that case. Should we perhaps create a High in any case?

Also `--torchserve-management-api-model-static-url` expects a single URL right now, should we add support for comma-separated list or is this enough?

2023-12-20 15:13 UTC, dawidg-doyen commented on doyensec/detectors/rce/torchserve/src/main/java/com/google/tsunami/plugins/detectors/rce/torchserve/TorchServeManagementApiDetector.java
> +  static final String REPORT_RECOMMENDATION =
Sorry I was referring to the recommendation line. So just to extend the text you have now       ```Disable the TorchServe Management API or restrict access to it.``` with some specific config changes if there are any to restrict access.

2023-12-20 17:03 UTC, execveat commented on doyensec/detectors/rce/torchserve/src/main/java/com/google/tsunami/plugins/detectors/rce/torchserve/TorchServeManagementApiDetector.java
> +  static final String REPORT_RECOMMENDATION =
Ah, I misunderstood. Here are the improved recommendations: https://github.com/doyensec/tsunami-security-scanner-plugins/blob/2e4576005b8c9ef135625db23d0777766e472873/doyensec/detectors/rce/torchserve/src/main/java/com/google/tsunami/plugins/detectors/rce/torchserve/TorchServeManagementApiDetector.java#L46-L67

2023-12-21 11:44 UTC, dawidg-doyen commented
Critical for confirmed RCE and High for fingerprint-based one seems right to me and is similar to what I did in Kubernetes detector. 

For just exposed API maybe you could add Low severity?

As for the static-url parameter I think it's fine as it is to keep it simple. I think the most important is the default run with default parameters. Not sure how often parameters will get adjusted in practice.

2023-12-22 17:26 UTC, merged